language: cpp
compiler:
    - clang
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make all && make all_tests.run

after_success:
    - sudo apt-get install --yes doxygen graphviz
    - ./publish-doxygen