language: cpp

compiler:
    - clang
    - gcc

install:
    - sudo apt-get install libboost-dev

before_script:
    - mkdir build
    - cd build
    - BUILD_ON_TRAVIS=1 cmake ..

script:
    - make all_tests && make all_tests.run

after_success:
    - sudo apt-get install --yes doxygen graphviz
    - ./publish-doxygen